name = "cf-workers-chatgpt-discord-bot"
main = "src/index.ts"
compatibility_date = "2023-03-02"
workers_dev = true



[vars]
CHATGPT_MODEL = "gpt-3.5-turbo"
CHATGPT_BEHAVIOR = ""
CONTEXT = 1
GEMINI_MODEL= "gemini-1.5-flash"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



